name: Print
on: push

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ vars.APP_NAME }}
      APP_KEY: ${{ secrets.APP_KEY }}
    steps:
      - name: Create text file
        run: |
          echo "App Name: $APP_NAME" > info.txt
          echo "App Key: $APP_KEY" >> info.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-info
          path: info.txt
        





