name: print

on: [push]

jobs:
  name: message
  runs-on: ubuntu-latest

  env:
    APP_NAME: ${{ vars.APP_NAME }}

  steps:

    - name: Checkout Repo
      run: actions/checkout@v4

    - name: Display
      run: echo "App Name: $APP_NAME"