name: print

on: [push]

jobs:
  message:
    name: Print Message
    runs-on: ubuntu-latest

  env:
    APP_NAME: ${{ vars.APP_NAME }}

  steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Display
      run: echo "App Name: $APP_NAME"