name: print

on:
  push:

jobs:
  message:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ vars.APP_NAME }}

    steps:
      - uses: actions/checkout@v4
      - run: echo "App Name: $APP_NAME"

