name: print

on:
  push:

env:
  APP_NAME: "hello"

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print (shell expansion)
        run: echo "App Name: $APP_NAME"
      - name: Print (Actions expression)
        run: echo "App Name: ${{ env.APP_NAME }}"
