name: PythonCICD

on: [push]

jobs:
  test-and-lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Requirements
        run: pip install flake8 pylint

      - name: Lint Hello.py
        run: |
          flake8 hello.py
          pylint hello.py

      - name: Test the script
        run: python hello.py | grep -i hello || exit 1 
